name: Tests Build
description: Setup Python and install cookicutter

runs:
  using: "composite"
  steps:
  - name: Setup Python
    uses: actions/setup-python@v5
    with:
      python-version: "3.10"
  - name: Install cookiecutter
    run: pip install cookiecutter
    shell: bash
